# --- File: act2.py ---
# Clean baseline for AI-driven Act 2 generation

act2_lore = {
    "summary": "To be generated by AI.",
    "major_events": [],
    "companions_bond_status": [],
    "traits_unlocked": [],
    "shrines_visited": [],
    "visions_echo_sequences": [],
    "lore_codex_expansions": [],
    "timeline_edits": [],
    "key_terms_introduced": [],
    "locations_realms_visited": [],
    "faction_threat_encounters": [],
    "oaths_rituals_performed": [],
    "artifacts_discovered": [],
    "narrative_threads_opened": [],
    "narrative_threads_closed": []
}
