# This workflow now triggers on a remote signal from the Streamlit app.

name: Lore Updater Bot

on:
  repository_dispatch:
    types: [update-lore] # This is the "button" our app will press

jobs:
  update-lore:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run Lore Update Pipeline
        working-directory: ./my_gm
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # The narrative log is now passed directly from the event
          NARRATIVE_LOG: ${{ github.event.client_payload.narrative_log }}
        run: python update_lore_pipeline.py

      - name: Commit and Push Changes
        working-directory: ./my_gm
        run: |
          git config --global user.name 'Lore Bot'
          git config --global user.email 'lore-bot@users.noreply.github.com'
          if git diff-index --quiet HEAD; then
            echo "No changes detected."
            exit 0
          fi
          git add -A
          git commit -m "Automated Lore Update"
          git push origin main