# This is the final, syntactically correct workflow file.
# It commits changes directly to the main branch.

name: Lore Updater Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-lore:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai gitpython

      - name: Run Lore Update Pipeline
        working-directory: "./My gm"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_lore_pipeline.py

      - name: Commit and Push Changes
        working-directory: "./My gm"
        run: |
          git config --global user.name 'Lore Bot'
          git config --global user.email 'lore-bot@users.noreply.github.com'
          
          if git diff-index --quiet HEAD; then
            echo "No changes detected by the script. Exiting."
            exit 0
          fi
          
          echo "Changes detected. Committing directly to main branch..."
          git add -A
          git commit -m "Automated Lore Update"
          git push origin main
