name: Lore Updater Bot

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  update-lore:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the correct version of Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Matches the version you specified

      # Step 3: Install the Python libraries your script needs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai gitpython

      # Step 4: Run the main pipeline script
      # This assumes your script is named "update_lore_pipeline.py"
      # and is in the root of your repository.
      - name: Run Lore Update Pipeline
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_lore_pipeline.py