name: Lore Updater Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-lore:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (no change)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (no change)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies (no change)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai gitpython

      # Step 4: Run your pipeline script (no change)
      - name: Run Lore Update Pipeline
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_lore_pipeline_gemini.py

      # --- UPGRADED STEP 5: Create a Pull Request Instead of Pushing to Main ---
      - name: Create Pull Request
        # This step uses the GitHub CLI, which is pre-installed on runners
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub
        run: |
          # Configure git with a bot user
          git config --global user.name 'Lore Bot'
          git config --global user.email 'lore-bot@users.noreply.github.com'

          # Check if there are any changes. If not, exit gracefully.
          if git diff-index --quiet HEAD; then
            echo "No changes to commit. Exiting."
            exit 0
          fi

          # Create a new branch with a unique name based on the date
          BRANCH_NAME="lore-update-$(date +%Y-%m-%d-%H%M%S)"
          git checkout -b $BRANCH_NAME

          # Add and commit the changes
          git add -A
          git commit -m "Automated Lore Update"
          
          # Push the new branch to the repository
          git push -u origin $BRANCH_NAME

          # Create the pull request
          gh pr create --base main --head $BRANCH_NAME --title "Automated Lore Update" --body "Please review the changes proposed by the Lore Bot. These changes were generated based on the latest narrative save job."